# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' DivisionConference Class
#'
#' @field id 
#' @field name 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DivisionConference <- R6::R6Class(
  'DivisionConference',
  public = list(
    id = NULL,
    name = NULL,
    link = NULL,
    initialize = function(id, name, link){
      if (!missing(id)) {
        stopifnot(is.numeric(id), length(id) == 1)
        stopifnot(R6::is.R6(id))
        self$id <- id
      }
      if (!missing(name)) {
        stopifnot(is.character(name), length(name) == 1)
        self$name <- name
      }
      if (!missing(link)) {
        stopifnot(is.character(link), length(link) == 1)
        self$link <- link
      }
    },
    toJSON = function() {
      DivisionConferenceObject <- list()
      if (!is.null(self$id)) {
        DivisionConferenceObject[['id']] <- self$id$toJSON()
      }
      if (!is.null(self$name)) {
        DivisionConferenceObject[['name']] <- self$name
      }
      if (!is.null(self$link)) {
        DivisionConferenceObject[['link']] <- self$link
      }

      DivisionConferenceObject
    },
    fromJSON = function(DivisionConferenceJson) {
      DivisionConferenceObject <- jsonlite::fromJSON(DivisionConferenceJson)
      if (!is.null(DivisionConferenceObject$id)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(DivisionConferenceObject$id, auto_unbox = TRUE))
        self$id <- idObject
      }
      if (!is.null(DivisionConferenceObject$name)) {
        self$name <- DivisionConferenceObject$name
      }
      if (!is.null(DivisionConferenceObject$link)) {
        self$link <- DivisionConferenceObject$link
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "link": %s
        }',
        self$id$toJSON(),
        self$name,
        self$link
      )
    },
    fromJSONString = function(DivisionConferenceJson) {
      DivisionConferenceObject <- jsonlite::fromJSON(DivisionConferenceJson)
      BigDecimalObject <- BigDecimal$new()
      self$id <- BigDecimalObject$fromJSON(jsonlite::toJSON(DivisionConferenceObject$id, auto_unbox = TRUE))
      self$name <- DivisionConferenceObject$name
      self$link <- DivisionConferenceObject$link
    }
  )
)
