# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' DraftProspectAmateurTeam Class
#'
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DraftProspectAmateurTeam <- R6::R6Class(
  'DraftProspectAmateurTeam',
  public = list(
    `link` = NULL,
    initialize = function(`link`){
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
    },
    toJSON = function() {
      DraftProspectAmateurTeamObject <- list()
      if (!is.null(self$`link`)) {
        DraftProspectAmateurTeamObject[['link']] <- self$`link`
      }

      DraftProspectAmateurTeamObject
    },
    fromJSON = function(DraftProspectAmateurTeamJson) {
      DraftProspectAmateurTeamObject <- jsonlite::fromJSON(DraftProspectAmateurTeamJson)
      if (!is.null(DraftProspectAmateurTeamObject$`link`)) {
        self$`link` <- DraftProspectAmateurTeamObject$`link`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "link": %s
        }',
        self$`link`
      )
    },
    fromJSONString = function(DraftProspectAmateurTeamJson) {
      DraftProspectAmateurTeamObject <- jsonlite::fromJSON(DraftProspectAmateurTeamJson)
      self$`link` <- DraftProspectAmateurTeamObject$`link`
    }
  )
)
