# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' DraftProspectAmateurLeague Class
#'
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DraftProspectAmateurLeague <- R6::R6Class(
  'DraftProspectAmateurLeague',
  public = list(
    link = NULL,
    initialize = function(link){
      if (!missing(link)) {
        stopifnot(is.character(link), length(link) == 1)
        self$link <- link
      }
    },
    toJSON = function() {
      DraftProspectAmateurLeagueObject <- list()
      if (!is.null(self$link)) {
        DraftProspectAmateurLeagueObject[['link']] <- self$link
      }

      DraftProspectAmateurLeagueObject
    },
    fromJSON = function(DraftProspectAmateurLeagueJson) {
      DraftProspectAmateurLeagueObject <- jsonlite::fromJSON(DraftProspectAmateurLeagueJson)
      if (!is.null(DraftProspectAmateurLeagueObject$link)) {
        self$link <- DraftProspectAmateurLeagueObject$link
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "link": %s
        }',
        self$link
      )
    },
    fromJSONString = function(DraftProspectAmateurLeagueJson) {
      DraftProspectAmateurLeagueObject <- jsonlite::fromJSON(DraftProspectAmateurLeagueJson)
      self$link <- DraftProspectAmateurLeagueObject$link
    }
  )
)
