# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameContent Class
#'
#' @field copyright 
#' @field link 
#' @field editorial 
#' @field media 
#' @field highlights 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameContent <- R6::R6Class(
  'GameContent',
  public = list(
    `copyright` = NULL,
    `link` = NULL,
    `editorial` = NULL,
    `media` = NULL,
    `highlights` = NULL,
    initialize = function(`copyright`, `link`, `editorial`, `media`, `highlights`){
      if (!missing(`copyright`)) {
        stopifnot(is.character(`copyright`), length(`copyright`) == 1)
        self$`copyright` <- `copyright`
      }
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
      if (!missing(`editorial`)) {
        stopifnot(R6::is.R6(`editorial`))
        self$`editorial` <- `editorial`
      }
      if (!missing(`media`)) {
        stopifnot(R6::is.R6(`media`))
        self$`media` <- `media`
      }
      if (!missing(`highlights`)) {
        stopifnot(R6::is.R6(`highlights`))
        self$`highlights` <- `highlights`
      }
    },
    toJSON = function() {
      GameContentObject <- list()
      if (!is.null(self$`copyright`)) {
        GameContentObject[['copyright']] <- self$`copyright`
      }
      if (!is.null(self$`link`)) {
        GameContentObject[['link']] <- self$`link`
      }
      if (!is.null(self$`editorial`)) {
        GameContentObject[['editorial']] <- self$`editorial`$toJSON()
      }
      if (!is.null(self$`media`)) {
        GameContentObject[['media']] <- self$`media`$toJSON()
      }
      if (!is.null(self$`highlights`)) {
        GameContentObject[['highlights']] <- self$`highlights`$toJSON()
      }

      GameContentObject
    },
    fromJSON = function(GameContentJson) {
      GameContentObject <- jsonlite::fromJSON(GameContentJson)
      if (!is.null(GameContentObject$`copyright`)) {
        self$`copyright` <- GameContentObject$`copyright`
      }
      if (!is.null(GameContentObject$`link`)) {
        self$`link` <- GameContentObject$`link`
      }
      if (!is.null(GameContentObject$`editorial`)) {
        editorialObject <- GameContentEditorial$new()
        editorialObject$fromJSON(jsonlite::toJSON(GameContentObject$editorial, auto_unbox = TRUE))
        self$`editorial` <- editorialObject
      }
      if (!is.null(GameContentObject$`media`)) {
        mediaObject <- GameContentMedia$new()
        mediaObject$fromJSON(jsonlite::toJSON(GameContentObject$media, auto_unbox = TRUE))
        self$`media` <- mediaObject
      }
      if (!is.null(GameContentObject$`highlights`)) {
        highlightsObject <- GameContentHighlights$new()
        highlightsObject$fromJSON(jsonlite::toJSON(GameContentObject$highlights, auto_unbox = TRUE))
        self$`highlights` <- highlightsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "copyright": %s,
           "link": %s,
           "editorial": %s,
           "media": %s,
           "highlights": %s
        }',
        self$`copyright`,
        self$`link`,
        self$`editorial`$toJSON(),
        self$`media`$toJSON(),
        self$`highlights`$toJSON()
      )
    },
    fromJSONString = function(GameContentJson) {
      GameContentObject <- jsonlite::fromJSON(GameContentJson)
      self$`copyright` <- GameContentObject$`copyright`
      self$`link` <- GameContentObject$`link`
      GameContentEditorialObject <- GameContentEditorial$new()
      self$`editorial` <- GameContentEditorialObject$fromJSON(jsonlite::toJSON(GameContentObject$editorial, auto_unbox = TRUE))
      GameContentMediaObject <- GameContentMedia$new()
      self$`media` <- GameContentMediaObject$fromJSON(jsonlite::toJSON(GameContentObject$media, auto_unbox = TRUE))
      GameContentHighlightsObject <- GameContentHighlights$new()
      self$`highlights` <- GameContentHighlightsObject$fromJSON(jsonlite::toJSON(GameContentObject$highlights, auto_unbox = TRUE))
    }
  )
)
