# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameContentHighlights Class
#'
#' @field scoreboard 
#' @field gameCenter 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameContentHighlights <- R6::R6Class(
  'GameContentHighlights',
  public = list(
    `scoreboard` = NULL,
    `gameCenter` = NULL,
    initialize = function(`scoreboard`, `gameCenter`){
      if (!missing(`scoreboard`)) {
        stopifnot(R6::is.R6(`scoreboard`))
        self$`scoreboard` <- `scoreboard`
      }
      if (!missing(`gameCenter`)) {
        stopifnot(R6::is.R6(`gameCenter`))
        self$`gameCenter` <- `gameCenter`
      }
    },
    toJSON = function() {
      GameContentHighlightsObject <- list()
      if (!is.null(self$`scoreboard`)) {
        GameContentHighlightsObject[['scoreboard']] <- self$`scoreboard`$toJSON()
      }
      if (!is.null(self$`gameCenter`)) {
        GameContentHighlightsObject[['gameCenter']] <- self$`gameCenter`$toJSON()
      }

      GameContentHighlightsObject
    },
    fromJSON = function(GameContentHighlightsJson) {
      GameContentHighlightsObject <- jsonlite::fromJSON(GameContentHighlightsJson)
      if (!is.null(GameContentHighlightsObject$`scoreboard`)) {
        scoreboardObject <- GameHighlights$new()
        scoreboardObject$fromJSON(jsonlite::toJSON(GameContentHighlightsObject$scoreboard, auto_unbox = TRUE))
        self$`scoreboard` <- scoreboardObject
      }
      if (!is.null(GameContentHighlightsObject$`gameCenter`)) {
        gameCenterObject <- GameHighlights$new()
        gameCenterObject$fromJSON(jsonlite::toJSON(GameContentHighlightsObject$gameCenter, auto_unbox = TRUE))
        self$`gameCenter` <- gameCenterObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "scoreboard": %s,
           "gameCenter": %s
        }',
        self$`scoreboard`$toJSON(),
        self$`gameCenter`$toJSON()
      )
    },
    fromJSONString = function(GameContentHighlightsJson) {
      GameContentHighlightsObject <- jsonlite::fromJSON(GameContentHighlightsJson)
      GameHighlightsObject <- GameHighlights$new()
      self$`scoreboard` <- GameHighlightsObject$fromJSON(jsonlite::toJSON(GameContentHighlightsObject$scoreboard, auto_unbox = TRUE))
      GameHighlightsObject <- GameHighlights$new()
      self$`gameCenter` <- GameHighlightsObject$fromJSON(jsonlite::toJSON(GameContentHighlightsObject$gameCenter, auto_unbox = TRUE))
    }
  )
)
