# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscoreTeamPerson Class
#'
#' @field fullName 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscoreTeamPerson <- R6::R6Class(
  'GameBoxscoreTeamPerson',
  public = list(
    fullName = NULL,
    link = NULL,
    initialize = function(fullName, link){
      if (!missing(fullName)) {
        stopifnot(is.character(fullName), length(fullName) == 1)
        self$fullName <- fullName
      }
      if (!missing(link)) {
        stopifnot(is.character(link), length(link) == 1)
        self$link <- link
      }
    },
    toJSON = function() {
      GameBoxscoreTeamPersonObject <- list()
      if (!is.null(self$fullName)) {
        GameBoxscoreTeamPersonObject[['fullName']] <- self$fullName
      }
      if (!is.null(self$link)) {
        GameBoxscoreTeamPersonObject[['link']] <- self$link
      }

      GameBoxscoreTeamPersonObject
    },
    fromJSON = function(GameBoxscoreTeamPersonJson) {
      GameBoxscoreTeamPersonObject <- jsonlite::fromJSON(GameBoxscoreTeamPersonJson)
      if (!is.null(GameBoxscoreTeamPersonObject$fullName)) {
        self$fullName <- GameBoxscoreTeamPersonObject$fullName
      }
      if (!is.null(GameBoxscoreTeamPersonObject$link)) {
        self$link <- GameBoxscoreTeamPersonObject$link
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "fullName": %s,
           "link": %s
        }',
        self$fullName,
        self$link
      )
    },
    fromJSONString = function(GameBoxscoreTeamPersonJson) {
      GameBoxscoreTeamPersonObject <- jsonlite::fromJSON(GameBoxscoreTeamPersonJson)
      self$fullName <- GameBoxscoreTeamPersonObject$fullName
      self$link <- GameBoxscoreTeamPersonObject$link
    }
  )
)
