# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameHighlights Class
#'
#' @field scoreboard 
#' @field gameCenter 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameHighlights <- R6::R6Class(
  'GameHighlights',
  public = list(
    `scoreboard` = NULL,
    `gameCenter` = NULL,
    initialize = function(`scoreboard`, `gameCenter`){
      if (!missing(`scoreboard`)) {
        stopifnot(R6::is.R6(`scoreboard`))
        self$`scoreboard` <- `scoreboard`
      }
      if (!missing(`gameCenter`)) {
        stopifnot(R6::is.R6(`gameCenter`))
        self$`gameCenter` <- `gameCenter`
      }
    },
    toJSON = function() {
      GameHighlightsObject <- list()
      if (!is.null(self$`scoreboard`)) {
        GameHighlightsObject[['scoreboard']] <- self$`scoreboard`$toJSON()
      }
      if (!is.null(self$`gameCenter`)) {
        GameHighlightsObject[['gameCenter']] <- self$`gameCenter`$toJSON()
      }

      GameHighlightsObject
    },
    fromJSON = function(GameHighlightsJson) {
      GameHighlightsObject <- jsonlite::fromJSON(GameHighlightsJson)
      if (!is.null(GameHighlightsObject$`scoreboard`)) {
        scoreboardObject <- GameHighlightType$new()
        scoreboardObject$fromJSON(jsonlite::toJSON(GameHighlightsObject$scoreboard, auto_unbox = TRUE))
        self$`scoreboard` <- scoreboardObject
      }
      if (!is.null(GameHighlightsObject$`gameCenter`)) {
        gameCenterObject <- GameHighlightType$new()
        gameCenterObject$fromJSON(jsonlite::toJSON(GameHighlightsObject$gameCenter, auto_unbox = TRUE))
        self$`gameCenter` <- gameCenterObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "scoreboard": %s,
           "gameCenter": %s
        }',
        self$`scoreboard`$toJSON(),
        self$`gameCenter`$toJSON()
      )
    },
    fromJSONString = function(GameHighlightsJson) {
      GameHighlightsObject <- jsonlite::fromJSON(GameHighlightsJson)
      GameHighlightTypeObject <- GameHighlightType$new()
      self$`scoreboard` <- GameHighlightTypeObject$fromJSON(jsonlite::toJSON(GameHighlightsObject$scoreboard, auto_unbox = TRUE))
      GameHighlightTypeObject <- GameHighlightType$new()
      self$`gameCenter` <- GameHighlightTypeObject$fromJSON(jsonlite::toJSON(GameHighlightsObject$gameCenter, auto_unbox = TRUE))
    }
  )
)
