# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameGameDataGame Class
#'
#' @field pk 
#' @field season 
#' @field type 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameGameDataGame <- R6::R6Class(
  'GameGameDataGame',
  public = list(
    pk = NULL,
    season = NULL,
    type = NULL,
    initialize = function(pk, season, type){
      if (!missing(pk)) {
        stopifnot(is.numeric(pk), length(pk) == 1)
        stopifnot(R6::is.R6(pk))
        self$pk <- pk
      }
      if (!missing(season)) {
        stopifnot(is.character(season), length(season) == 1)
        self$season <- season
      }
      if (!missing(type)) {
        stopifnot(is.character(type), length(type) == 1)
        self$type <- type
      }
    },
    toJSON = function() {
      GameGameDataGameObject <- list()
      if (!is.null(self$pk)) {
        GameGameDataGameObject[['pk']] <- self$pk$toJSON()
      }
      if (!is.null(self$season)) {
        GameGameDataGameObject[['season']] <- self$season
      }
      if (!is.null(self$type)) {
        GameGameDataGameObject[['type']] <- self$type
      }

      GameGameDataGameObject
    },
    fromJSON = function(GameGameDataGameJson) {
      GameGameDataGameObject <- jsonlite::fromJSON(GameGameDataGameJson)
      if (!is.null(GameGameDataGameObject$pk)) {
        pkObject <- BigDecimal$new()
        pkObject$fromJSON(jsonlite::toJSON(GameGameDataGameObject$pk, auto_unbox = TRUE))
        self$pk <- pkObject
      }
      if (!is.null(GameGameDataGameObject$season)) {
        self$season <- GameGameDataGameObject$season
      }
      if (!is.null(GameGameDataGameObject$type)) {
        self$type <- GameGameDataGameObject$type
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "pk": %s,
           "season": %s,
           "type": %s
        }',
        self$pk$toJSON(),
        self$season,
        self$type
      )
    },
    fromJSONString = function(GameGameDataGameJson) {
      GameGameDataGameObject <- jsonlite::fromJSON(GameGameDataGameJson)
      BigDecimalObject <- BigDecimal$new()
      self$pk <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameGameDataGameObject$pk, auto_unbox = TRUE))
      self$season <- GameGameDataGameObject$season
      self$type <- GameGameDataGameObject$type
    }
  )
)
