# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameOfficialOfficial Class
#'
#' @field id 
#' @field fullName 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameOfficialOfficial <- R6::R6Class(
  'GameOfficialOfficial',
  public = list(
    `id` = NULL,
    `fullName` = NULL,
    `link` = NULL,
    initialize = function(`id`, `fullName`, `link`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!missing(`fullName`)) {
        stopifnot(is.character(`fullName`), length(`fullName`) == 1)
        self$`fullName` <- `fullName`
      }
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
    },
    toJSON = function() {
      GameOfficialOfficialObject <- list()
      if (!is.null(self$`id`)) {
        GameOfficialOfficialObject[['id']] <- self$`id`$toJSON()
      }
      if (!is.null(self$`fullName`)) {
        GameOfficialOfficialObject[['fullName']] <- self$`fullName`
      }
      if (!is.null(self$`link`)) {
        GameOfficialOfficialObject[['link']] <- self$`link`
      }

      GameOfficialOfficialObject
    },
    fromJSON = function(GameOfficialOfficialJson) {
      GameOfficialOfficialObject <- jsonlite::fromJSON(GameOfficialOfficialJson)
      if (!is.null(GameOfficialOfficialObject$`id`)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(GameOfficialOfficialObject$id, auto_unbox = TRUE))
        self$`id` <- idObject
      }
      if (!is.null(GameOfficialOfficialObject$`fullName`)) {
        self$`fullName` <- GameOfficialOfficialObject$`fullName`
      }
      if (!is.null(GameOfficialOfficialObject$`link`)) {
        self$`link` <- GameOfficialOfficialObject$`link`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "fullName": %s,
           "link": %s
        }',
        self$`id`$toJSON(),
        self$`fullName`,
        self$`link`
      )
    },
    fromJSONString = function(GameOfficialOfficialJson) {
      GameOfficialOfficialObject <- jsonlite::fromJSON(GameOfficialOfficialJson)
      BigDecimalObject <- BigDecimal$new()
      self$`id` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameOfficialOfficialObject$id, auto_unbox = TRUE))
      self$`fullName` <- GameOfficialOfficialObject$`fullName`
      self$`link` <- GameOfficialOfficialObject$`link`
    }
  )
)
