# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameGameDataStatus Class
#'
#' @field abstractGameState 
#' @field codedGameState 
#' @field detailedState 
#' @field statusCode 
#' @field startTimeTBD 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameGameDataStatus <- R6::R6Class(
  'GameGameDataStatus',
  public = list(
    abstractGameState = NULL,
    codedGameState = NULL,
    detailedState = NULL,
    statusCode = NULL,
    startTimeTBD = NULL,
    initialize = function(abstractGameState, codedGameState, detailedState, statusCode, startTimeTBD){
      if (!missing(abstractGameState)) {
        stopifnot(is.character(abstractGameState), length(abstractGameState) == 1)
        self$abstractGameState <- abstractGameState
      }
      if (!missing(codedGameState)) {
        stopifnot(is.character(codedGameState), length(codedGameState) == 1)
        self$codedGameState <- codedGameState
      }
      if (!missing(detailedState)) {
        stopifnot(is.character(detailedState), length(detailedState) == 1)
        self$detailedState <- detailedState
      }
      if (!missing(statusCode)) {
        stopifnot(is.character(statusCode), length(statusCode) == 1)
        self$statusCode <- statusCode
      }
      if (!missing(startTimeTBD)) {
        self$startTimeTBD <- startTimeTBD
      }
    },
    toJSON = function() {
      GameGameDataStatusObject <- list()
      if (!is.null(self$abstractGameState)) {
        GameGameDataStatusObject[['abstractGameState']] <- self$abstractGameState
      }
      if (!is.null(self$codedGameState)) {
        GameGameDataStatusObject[['codedGameState']] <- self$codedGameState
      }
      if (!is.null(self$detailedState)) {
        GameGameDataStatusObject[['detailedState']] <- self$detailedState
      }
      if (!is.null(self$statusCode)) {
        GameGameDataStatusObject[['statusCode']] <- self$statusCode
      }
      if (!is.null(self$startTimeTBD)) {
        GameGameDataStatusObject[['startTimeTBD']] <- self$startTimeTBD
      }

      GameGameDataStatusObject
    },
    fromJSON = function(GameGameDataStatusJson) {
      GameGameDataStatusObject <- jsonlite::fromJSON(GameGameDataStatusJson)
      if (!is.null(GameGameDataStatusObject$abstractGameState)) {
        self$abstractGameState <- GameGameDataStatusObject$abstractGameState
      }
      if (!is.null(GameGameDataStatusObject$codedGameState)) {
        self$codedGameState <- GameGameDataStatusObject$codedGameState
      }
      if (!is.null(GameGameDataStatusObject$detailedState)) {
        self$detailedState <- GameGameDataStatusObject$detailedState
      }
      if (!is.null(GameGameDataStatusObject$statusCode)) {
        self$statusCode <- GameGameDataStatusObject$statusCode
      }
      if (!is.null(GameGameDataStatusObject$startTimeTBD)) {
        self$startTimeTBD <- GameGameDataStatusObject$startTimeTBD
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "abstractGameState": %s,
           "codedGameState": %s,
           "detailedState": %s,
           "statusCode": %s,
           "startTimeTBD": %s
        }',
        self$abstractGameState,
        self$codedGameState,
        self$detailedState,
        self$statusCode,
        self$startTimeTBD
      )
    },
    fromJSONString = function(GameGameDataStatusJson) {
      GameGameDataStatusObject <- jsonlite::fromJSON(GameGameDataStatusJson)
      self$abstractGameState <- GameGameDataStatusObject$abstractGameState
      self$codedGameState <- GameGameDataStatusObject$codedGameState
      self$detailedState <- GameGameDataStatusObject$detailedState
      self$statusCode <- GameGameDataStatusObject$statusCode
      self$startTimeTBD <- GameGameDataStatusObject$startTimeTBD
    }
  )
)
