# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameHighlightType Class
#'
#' @field title 
#' @field topicList 
#' @field items 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameHighlightType <- R6::R6Class(
  'GameHighlightType',
  public = list(
    title = NULL,
    topicList = NULL,
    items = NULL,
    initialize = function(title, topicList, items){
      if (!missing(title)) {
        stopifnot(is.character(title), length(title) == 1)
        self$title <- title
      }
      if (!missing(topicList)) {
        stopifnot(is.character(topicList), length(topicList) == 1)
        self$topicList <- topicList
      }
      if (!missing(items)) {
        stopifnot(is.list(items), length(items) != 0)
        lapply(items, function(x) stopifnot(R6::is.R6(x)))
        self$items <- items
      }
    },
    toJSON = function() {
      GameHighlightTypeObject <- list()
      if (!is.null(self$title)) {
        GameHighlightTypeObject[['title']] <- self$title
      }
      if (!is.null(self$topicList)) {
        GameHighlightTypeObject[['topicList']] <- self$topicList
      }
      if (!is.null(self$items)) {
        GameHighlightTypeObject[['items']] <- lapply(self$items, function(x) x$toJSON())
      }

      GameHighlightTypeObject
    },
    fromJSON = function(GameHighlightTypeJson) {
      GameHighlightTypeObject <- jsonlite::fromJSON(GameHighlightTypeJson)
      if (!is.null(GameHighlightTypeObject$title)) {
        self$title <- GameHighlightTypeObject$title
      }
      if (!is.null(GameHighlightTypeObject$topicList)) {
        self$topicList <- GameHighlightTypeObject$topicList
      }
      if (!is.null(GameHighlightTypeObject$items)) {
        self$items <- lapply(GameHighlightTypeObject$items, function(x) {
          itemsObject <- GameHighlight$new()
          itemsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          itemsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": %s,
           "topicList": %s,
           "items": [%s]
        }',
        self$title,
        self$topicList,
        lapply(self$items, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GameHighlightTypeJson) {
      GameHighlightTypeObject <- jsonlite::fromJSON(GameHighlightTypeJson)
      self$title <- GameHighlightTypeObject$title
      self$topicList <- GameHighlightTypeObject$topicList
      self$items <- lapply(GameHighlightTypeObject$items, function(x) GameHighlight$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
