# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscoreTeamTeam Class
#'
#' @field id 
#' @field name 
#' @field link 
#' @field abbreviation 
#' @field triCode 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscoreTeamTeam <- R6::R6Class(
  'GameBoxscoreTeamTeam',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `link` = NULL,
    `abbreviation` = NULL,
    `triCode` = NULL,
    initialize = function(`id`, `name`, `link`, `abbreviation`, `triCode`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
      if (!missing(`abbreviation`)) {
        stopifnot(is.character(`abbreviation`), length(`abbreviation`) == 1)
        self$`abbreviation` <- `abbreviation`
      }
      if (!missing(`triCode`)) {
        stopifnot(is.character(`triCode`), length(`triCode`) == 1)
        self$`triCode` <- `triCode`
      }
    },
    toJSON = function() {
      GameBoxscoreTeamTeamObject <- list()
      if (!is.null(self$`id`)) {
        GameBoxscoreTeamTeamObject[['id']] <- self$`id`$toJSON()
      }
      if (!is.null(self$`name`)) {
        GameBoxscoreTeamTeamObject[['name']] <- self$`name`
      }
      if (!is.null(self$`link`)) {
        GameBoxscoreTeamTeamObject[['link']] <- self$`link`
      }
      if (!is.null(self$`abbreviation`)) {
        GameBoxscoreTeamTeamObject[['abbreviation']] <- self$`abbreviation`
      }
      if (!is.null(self$`triCode`)) {
        GameBoxscoreTeamTeamObject[['triCode']] <- self$`triCode`
      }

      GameBoxscoreTeamTeamObject
    },
    fromJSON = function(GameBoxscoreTeamTeamJson) {
      GameBoxscoreTeamTeamObject <- jsonlite::fromJSON(GameBoxscoreTeamTeamJson)
      if (!is.null(GameBoxscoreTeamTeamObject$`id`)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamTeamObject$id, auto_unbox = TRUE))
        self$`id` <- idObject
      }
      if (!is.null(GameBoxscoreTeamTeamObject$`name`)) {
        self$`name` <- GameBoxscoreTeamTeamObject$`name`
      }
      if (!is.null(GameBoxscoreTeamTeamObject$`link`)) {
        self$`link` <- GameBoxscoreTeamTeamObject$`link`
      }
      if (!is.null(GameBoxscoreTeamTeamObject$`abbreviation`)) {
        self$`abbreviation` <- GameBoxscoreTeamTeamObject$`abbreviation`
      }
      if (!is.null(GameBoxscoreTeamTeamObject$`triCode`)) {
        self$`triCode` <- GameBoxscoreTeamTeamObject$`triCode`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "link": %s,
           "abbreviation": %s,
           "triCode": %s
        }',
        self$`id`$toJSON(),
        self$`name`,
        self$`link`,
        self$`abbreviation`,
        self$`triCode`
      )
    },
    fromJSONString = function(GameBoxscoreTeamTeamJson) {
      GameBoxscoreTeamTeamObject <- jsonlite::fromJSON(GameBoxscoreTeamTeamJson)
      BigDecimalObject <- BigDecimal$new()
      self$`id` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamTeamObject$id, auto_unbox = TRUE))
      self$`name` <- GameBoxscoreTeamTeamObject$`name`
      self$`link` <- GameBoxscoreTeamTeamObject$`link`
      self$`abbreviation` <- GameBoxscoreTeamTeamObject$`abbreviation`
      self$`triCode` <- GameBoxscoreTeamTeamObject$`triCode`
    }
  )
)
