# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GamePlayResult Class
#'
#' @field event 
#' @field eventCode 
#' @field eventTypeId 
#' @field description 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GamePlayResult <- R6::R6Class(
  'GamePlayResult',
  public = list(
    `event` = NULL,
    `eventCode` = NULL,
    `eventTypeId` = NULL,
    `description` = NULL,
    initialize = function(`event`, `eventCode`, `eventTypeId`, `description`){
      if (!missing(`event`)) {
        stopifnot(is.character(`event`), length(`event`) == 1)
        self$`event` <- `event`
      }
      if (!missing(`eventCode`)) {
        stopifnot(is.character(`eventCode`), length(`eventCode`) == 1)
        self$`eventCode` <- `eventCode`
      }
      if (!missing(`eventTypeId`)) {
        stopifnot(is.character(`eventTypeId`), length(`eventTypeId`) == 1)
        self$`eventTypeId` <- `eventTypeId`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      GamePlayResultObject <- list()
      if (!is.null(self$`event`)) {
        GamePlayResultObject[['event']] <- self$`event`
      }
      if (!is.null(self$`eventCode`)) {
        GamePlayResultObject[['eventCode']] <- self$`eventCode`
      }
      if (!is.null(self$`eventTypeId`)) {
        GamePlayResultObject[['eventTypeId']] <- self$`eventTypeId`
      }
      if (!is.null(self$`description`)) {
        GamePlayResultObject[['description']] <- self$`description`
      }

      GamePlayResultObject
    },
    fromJSON = function(GamePlayResultJson) {
      GamePlayResultObject <- jsonlite::fromJSON(GamePlayResultJson)
      if (!is.null(GamePlayResultObject$`event`)) {
        self$`event` <- GamePlayResultObject$`event`
      }
      if (!is.null(GamePlayResultObject$`eventCode`)) {
        self$`eventCode` <- GamePlayResultObject$`eventCode`
      }
      if (!is.null(GamePlayResultObject$`eventTypeId`)) {
        self$`eventTypeId` <- GamePlayResultObject$`eventTypeId`
      }
      if (!is.null(GamePlayResultObject$`description`)) {
        self$`description` <- GamePlayResultObject$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "event": %s,
           "eventCode": %s,
           "eventTypeId": %s,
           "description": %s
        }',
        self$`event`,
        self$`eventCode`,
        self$`eventTypeId`,
        self$`description`
      )
    },
    fromJSONString = function(GamePlayResultJson) {
      GamePlayResultObject <- jsonlite::fromJSON(GamePlayResultJson)
      self$`event` <- GamePlayResultObject$`event`
      self$`eventCode` <- GamePlayResultObject$`eventCode`
      self$`eventTypeId` <- GamePlayResultObject$`eventTypeId`
      self$`description` <- GamePlayResultObject$`description`
    }
  )
)
