# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameEditorials Class
#'
#' @field title 
#' @field topicList 
#' @field items 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameEditorials <- R6::R6Class(
  'GameEditorials',
  public = list(
    title = NULL,
    topicList = NULL,
    items = NULL,
    initialize = function(title, topicList, items){
      if (!missing(title)) {
        stopifnot(is.character(title), length(title) == 1)
        self$title <- title
      }
      if (!missing(topicList)) {
        stopifnot(is.character(topicList), length(topicList) == 1)
        self$topicList <- topicList
      }
      if (!missing(items)) {
        stopifnot(is.list(items), length(items) != 0)
        lapply(items, function(x) stopifnot(R6::is.R6(x)))
        self$items <- items
      }
    },
    toJSON = function() {
      GameEditorialsObject <- list()
      if (!is.null(self$title)) {
        GameEditorialsObject[['title']] <- self$title
      }
      if (!is.null(self$topicList)) {
        GameEditorialsObject[['topicList']] <- self$topicList
      }
      if (!is.null(self$items)) {
        GameEditorialsObject[['items']] <- lapply(self$items, function(x) x$toJSON())
      }

      GameEditorialsObject
    },
    fromJSON = function(GameEditorialsJson) {
      GameEditorialsObject <- jsonlite::fromJSON(GameEditorialsJson)
      if (!is.null(GameEditorialsObject$title)) {
        self$title <- GameEditorialsObject$title
      }
      if (!is.null(GameEditorialsObject$topicList)) {
        self$topicList <- GameEditorialsObject$topicList
      }
      if (!is.null(GameEditorialsObject$items)) {
        self$items <- lapply(GameEditorialsObject$items, function(x) {
          itemsObject <- GameEditorial$new()
          itemsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          itemsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": %s,
           "topicList": %s,
           "items": [%s]
        }',
        self$title,
        self$topicList,
        lapply(self$items, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GameEditorialsJson) {
      GameEditorialsObject <- jsonlite::fromJSON(GameEditorialsJson)
      self$title <- GameEditorialsObject$title
      self$topicList <- GameEditorialsObject$topicList
      self$items <- lapply(GameEditorialsObject$items, function(x) GameEditorial$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
