# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscores Class
#'
#' @field teams 
#' @field officials 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscores <- R6::R6Class(
  'GameBoxscores',
  public = list(
    teams = NULL,
    officials = NULL,
    initialize = function(teams, officials){
      if (!missing(teams)) {
        stopifnot(R6::is.R6(teams))
        self$teams <- teams
      }
      if (!missing(officials)) {
        stopifnot(is.list(officials), length(officials) != 0)
        lapply(officials, function(x) stopifnot(R6::is.R6(x)))
        self$officials <- officials
      }
    },
    toJSON = function() {
      GameBoxscoresObject <- list()
      if (!is.null(self$teams)) {
        GameBoxscoresObject[['teams']] <- self$teams$toJSON()
      }
      if (!is.null(self$officials)) {
        GameBoxscoresObject[['officials']] <- lapply(self$officials, function(x) x$toJSON())
      }

      GameBoxscoresObject
    },
    fromJSON = function(GameBoxscoresJson) {
      GameBoxscoresObject <- jsonlite::fromJSON(GameBoxscoresJson)
      if (!is.null(GameBoxscoresObject$teams)) {
        teamsObject <- GameBoxscoreTeams$new()
        teamsObject$fromJSON(jsonlite::toJSON(GameBoxscoresObject$teams, auto_unbox = TRUE))
        self$teams <- teamsObject
      }
      if (!is.null(GameBoxscoresObject$officials)) {
        self$officials <- lapply(GameBoxscoresObject$officials, function(x) {
          officialsObject <- GameOfficial$new()
          officialsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          officialsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "teams": %s,
           "officials": [%s]
        }',
        self$teams$toJSON(),
        lapply(self$officials, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GameBoxscoresJson) {
      GameBoxscoresObject <- jsonlite::fromJSON(GameBoxscoresJson)
      GameBoxscoreTeamsObject <- GameBoxscoreTeams$new()
      self$teams <- GameBoxscoreTeamsObject$fromJSON(jsonlite::toJSON(GameBoxscoresObject$teams, auto_unbox = TRUE))
      self$officials <- lapply(GameBoxscoresObject$officials, function(x) GameOfficial$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
