# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameEditorialTokenData Class
#'
#' @field tokenGUID 
#' @field type 
#' @field id 
#' @field teamId 
#' @field name 
#' @field seoName 
#' @field href 
#' @field hrefMobile 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameEditorialTokenData <- R6::R6Class(
  'GameEditorialTokenData',
  public = list(
    `tokenGUID` = NULL,
    `type` = NULL,
    `id` = NULL,
    `teamId` = NULL,
    `name` = NULL,
    `seoName` = NULL,
    `href` = NULL,
    `hrefMobile` = NULL,
    initialize = function(`tokenGUID`, `type`, `id`, `teamId`, `name`, `seoName`, `href`, `hrefMobile`){
      if (!missing(`tokenGUID`)) {
        stopifnot(is.character(`tokenGUID`), length(`tokenGUID`) == 1)
        self$`tokenGUID` <- `tokenGUID`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`teamId`)) {
        stopifnot(is.character(`teamId`), length(`teamId`) == 1)
        self$`teamId` <- `teamId`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`seoName`)) {
        stopifnot(is.character(`seoName`), length(`seoName`) == 1)
        self$`seoName` <- `seoName`
      }
      if (!missing(`href`)) {
        stopifnot(is.character(`href`), length(`href`) == 1)
        self$`href` <- `href`
      }
      if (!missing(`hrefMobile`)) {
        stopifnot(is.character(`hrefMobile`), length(`hrefMobile`) == 1)
        self$`hrefMobile` <- `hrefMobile`
      }
    },
    toJSON = function() {
      GameEditorialTokenDataObject <- list()
      if (!is.null(self$`tokenGUID`)) {
        GameEditorialTokenDataObject[['tokenGUID']] <- self$`tokenGUID`
      }
      if (!is.null(self$`type`)) {
        GameEditorialTokenDataObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        GameEditorialTokenDataObject[['id']] <- self$`id`
      }
      if (!is.null(self$`teamId`)) {
        GameEditorialTokenDataObject[['teamId']] <- self$`teamId`
      }
      if (!is.null(self$`name`)) {
        GameEditorialTokenDataObject[['name']] <- self$`name`
      }
      if (!is.null(self$`seoName`)) {
        GameEditorialTokenDataObject[['seoName']] <- self$`seoName`
      }
      if (!is.null(self$`href`)) {
        GameEditorialTokenDataObject[['href']] <- self$`href`
      }
      if (!is.null(self$`hrefMobile`)) {
        GameEditorialTokenDataObject[['hrefMobile']] <- self$`hrefMobile`
      }

      GameEditorialTokenDataObject
    },
    fromJSON = function(GameEditorialTokenDataJson) {
      GameEditorialTokenDataObject <- jsonlite::fromJSON(GameEditorialTokenDataJson)
      if (!is.null(GameEditorialTokenDataObject$`tokenGUID`)) {
        self$`tokenGUID` <- GameEditorialTokenDataObject$`tokenGUID`
      }
      if (!is.null(GameEditorialTokenDataObject$`type`)) {
        self$`type` <- GameEditorialTokenDataObject$`type`
      }
      if (!is.null(GameEditorialTokenDataObject$`id`)) {
        self$`id` <- GameEditorialTokenDataObject$`id`
      }
      if (!is.null(GameEditorialTokenDataObject$`teamId`)) {
        self$`teamId` <- GameEditorialTokenDataObject$`teamId`
      }
      if (!is.null(GameEditorialTokenDataObject$`name`)) {
        self$`name` <- GameEditorialTokenDataObject$`name`
      }
      if (!is.null(GameEditorialTokenDataObject$`seoName`)) {
        self$`seoName` <- GameEditorialTokenDataObject$`seoName`
      }
      if (!is.null(GameEditorialTokenDataObject$`href`)) {
        self$`href` <- GameEditorialTokenDataObject$`href`
      }
      if (!is.null(GameEditorialTokenDataObject$`hrefMobile`)) {
        self$`hrefMobile` <- GameEditorialTokenDataObject$`hrefMobile`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "tokenGUID": %s,
           "type": %s,
           "id": %s,
           "teamId": %s,
           "name": %s,
           "seoName": %s,
           "href": %s,
           "hrefMobile": %s
        }',
        self$`tokenGUID`,
        self$`type`,
        self$`id`,
        self$`teamId`,
        self$`name`,
        self$`seoName`,
        self$`href`,
        self$`hrefMobile`
      )
    },
    fromJSONString = function(GameEditorialTokenDataJson) {
      GameEditorialTokenDataObject <- jsonlite::fromJSON(GameEditorialTokenDataJson)
      self$`tokenGUID` <- GameEditorialTokenDataObject$`tokenGUID`
      self$`type` <- GameEditorialTokenDataObject$`type`
      self$`id` <- GameEditorialTokenDataObject$`id`
      self$`teamId` <- GameEditorialTokenDataObject$`teamId`
      self$`name` <- GameEditorialTokenDataObject$`name`
      self$`seoName` <- GameEditorialTokenDataObject$`seoName`
      self$`href` <- GameEditorialTokenDataObject$`href`
      self$`hrefMobile` <- GameEditorialTokenDataObject$`hrefMobile`
    }
  )
)
