# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscoreTeams Class
#'
#' @field away 
#' @field home 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscoreTeams <- R6::R6Class(
  'GameBoxscoreTeams',
  public = list(
    `away` = NULL,
    `home` = NULL,
    initialize = function(`away`, `home`){
      if (!missing(`away`)) {
        stopifnot(R6::is.R6(`away`))
        self$`away` <- `away`
      }
      if (!missing(`home`)) {
        stopifnot(R6::is.R6(`home`))
        self$`home` <- `home`
      }
    },
    toJSON = function() {
      GameBoxscoreTeamsObject <- list()
      if (!is.null(self$`away`)) {
        GameBoxscoreTeamsObject[['away']] <- self$`away`$toJSON()
      }
      if (!is.null(self$`home`)) {
        GameBoxscoreTeamsObject[['home']] <- self$`home`$toJSON()
      }

      GameBoxscoreTeamsObject
    },
    fromJSON = function(GameBoxscoreTeamsJson) {
      GameBoxscoreTeamsObject <- jsonlite::fromJSON(GameBoxscoreTeamsJson)
      if (!is.null(GameBoxscoreTeamsObject$`away`)) {
        awayObject <- GameBoxscoreTeam$new()
        awayObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamsObject$away, auto_unbox = TRUE))
        self$`away` <- awayObject
      }
      if (!is.null(GameBoxscoreTeamsObject$`home`)) {
        homeObject <- GameBoxscoreTeam$new()
        homeObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamsObject$home, auto_unbox = TRUE))
        self$`home` <- homeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "away": %s,
           "home": %s
        }',
        self$`away`$toJSON(),
        self$`home`$toJSON()
      )
    },
    fromJSONString = function(GameBoxscoreTeamsJson) {
      GameBoxscoreTeamsObject <- jsonlite::fromJSON(GameBoxscoreTeamsJson)
      GameBoxscoreTeamObject <- GameBoxscoreTeam$new()
      self$`away` <- GameBoxscoreTeamObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamsObject$away, auto_unbox = TRUE))
      GameBoxscoreTeamObject <- GameBoxscoreTeam$new()
      self$`home` <- GameBoxscoreTeamObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamsObject$home, auto_unbox = TRUE))
    }
  )
)
