# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscoreTeamPlayersStats Class
#'
#' @field skaterStats 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscoreTeamPlayersStats <- R6::R6Class(
  'GameBoxscoreTeamPlayersStats',
  public = list(
    `skaterStats` = NULL,
    initialize = function(`skaterStats`){
      if (!missing(`skaterStats`)) {
        stopifnot(R6::is.R6(`skaterStats`))
        self$`skaterStats` <- `skaterStats`
      }
    },
    toJSON = function() {
      GameBoxscoreTeamPlayersStatsObject <- list()
      if (!is.null(self$`skaterStats`)) {
        GameBoxscoreTeamPlayersStatsObject[['skaterStats']] <- self$`skaterStats`$toJSON()
      }

      GameBoxscoreTeamPlayersStatsObject
    },
    fromJSON = function(GameBoxscoreTeamPlayersStatsJson) {
      GameBoxscoreTeamPlayersStatsObject <- jsonlite::fromJSON(GameBoxscoreTeamPlayersStatsJson)
      if (!is.null(GameBoxscoreTeamPlayersStatsObject$`skaterStats`)) {
        skaterStatsObject <- GameBoxscoreTeamPlayersStatsSkaterStats$new()
        skaterStatsObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamPlayersStatsObject$skaterStats, auto_unbox = TRUE))
        self$`skaterStats` <- skaterStatsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "skaterStats": %s
        }',
        self$`skaterStats`$toJSON()
      )
    },
    fromJSONString = function(GameBoxscoreTeamPlayersStatsJson) {
      GameBoxscoreTeamPlayersStatsObject <- jsonlite::fromJSON(GameBoxscoreTeamPlayersStatsJson)
      GameBoxscoreTeamPlayersStatsSkaterStatsObject <- GameBoxscoreTeamPlayersStatsSkaterStats$new()
      self$`skaterStats` <- GameBoxscoreTeamPlayersStatsSkaterStatsObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamPlayersStatsObject$skaterStats, auto_unbox = TRUE))
    }
  )
)
