# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GamePlayAbout Class
#'
#' @field eventIdx 
#' @field eventId 
#' @field period 
#' @field periodType 
#' @field ordinalNum 
#' @field periodTime 
#' @field periodTimeRemaining 
#' @field dateTime 
#' @field goals 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GamePlayAbout <- R6::R6Class(
  'GamePlayAbout',
  public = list(
    `eventIdx` = NULL,
    `eventId` = NULL,
    `period` = NULL,
    `periodType` = NULL,
    `ordinalNum` = NULL,
    `periodTime` = NULL,
    `periodTimeRemaining` = NULL,
    `dateTime` = NULL,
    `goals` = NULL,
    initialize = function(`eventIdx`, `eventId`, `period`, `periodType`, `ordinalNum`, `periodTime`, `periodTimeRemaining`, `dateTime`, `goals`){
      if (!missing(`eventIdx`)) {
        stopifnot(is.numeric(`eventIdx`), length(`eventIdx`) == 1)
        stopifnot(R6::is.R6(`eventIdx`))
        self$`eventIdx` <- `eventIdx`
      }
      if (!missing(`eventId`)) {
        stopifnot(is.numeric(`eventId`), length(`eventId`) == 1)
        stopifnot(R6::is.R6(`eventId`))
        self$`eventId` <- `eventId`
      }
      if (!missing(`period`)) {
        stopifnot(is.numeric(`period`), length(`period`) == 1)
        stopifnot(R6::is.R6(`period`))
        self$`period` <- `period`
      }
      if (!missing(`periodType`)) {
        stopifnot(is.character(`periodType`), length(`periodType`) == 1)
        self$`periodType` <- `periodType`
      }
      if (!missing(`ordinalNum`)) {
        stopifnot(is.character(`ordinalNum`), length(`ordinalNum`) == 1)
        self$`ordinalNum` <- `ordinalNum`
      }
      if (!missing(`periodTime`)) {
        stopifnot(is.character(`periodTime`), length(`periodTime`) == 1)
        self$`periodTime` <- `periodTime`
      }
      if (!missing(`periodTimeRemaining`)) {
        stopifnot(is.character(`periodTimeRemaining`), length(`periodTimeRemaining`) == 1)
        self$`periodTimeRemaining` <- `periodTimeRemaining`
      }
      if (!missing(`dateTime`)) {
        stopifnot(is.character(`dateTime`), length(`dateTime`) == 1)
        self$`dateTime` <- `dateTime`
      }
      if (!missing(`goals`)) {
        stopifnot(R6::is.R6(`goals`))
        self$`goals` <- `goals`
      }
    },
    toJSON = function() {
      GamePlayAboutObject <- list()
      if (!is.null(self$`eventIdx`)) {
        GamePlayAboutObject[['eventIdx']] <- self$`eventIdx`$toJSON()
      }
      if (!is.null(self$`eventId`)) {
        GamePlayAboutObject[['eventId']] <- self$`eventId`$toJSON()
      }
      if (!is.null(self$`period`)) {
        GamePlayAboutObject[['period']] <- self$`period`$toJSON()
      }
      if (!is.null(self$`periodType`)) {
        GamePlayAboutObject[['periodType']] <- self$`periodType`
      }
      if (!is.null(self$`ordinalNum`)) {
        GamePlayAboutObject[['ordinalNum']] <- self$`ordinalNum`
      }
      if (!is.null(self$`periodTime`)) {
        GamePlayAboutObject[['periodTime']] <- self$`periodTime`
      }
      if (!is.null(self$`periodTimeRemaining`)) {
        GamePlayAboutObject[['periodTimeRemaining']] <- self$`periodTimeRemaining`
      }
      if (!is.null(self$`dateTime`)) {
        GamePlayAboutObject[['dateTime']] <- self$`dateTime`
      }
      if (!is.null(self$`goals`)) {
        GamePlayAboutObject[['goals']] <- self$`goals`$toJSON()
      }

      GamePlayAboutObject
    },
    fromJSON = function(GamePlayAboutJson) {
      GamePlayAboutObject <- jsonlite::fromJSON(GamePlayAboutJson)
      if (!is.null(GamePlayAboutObject$`eventIdx`)) {
        eventIdxObject <- BigDecimal$new()
        eventIdxObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$eventIdx, auto_unbox = TRUE))
        self$`eventIdx` <- eventIdxObject
      }
      if (!is.null(GamePlayAboutObject$`eventId`)) {
        eventIdObject <- BigDecimal$new()
        eventIdObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$eventId, auto_unbox = TRUE))
        self$`eventId` <- eventIdObject
      }
      if (!is.null(GamePlayAboutObject$`period`)) {
        periodObject <- BigDecimal$new()
        periodObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$period, auto_unbox = TRUE))
        self$`period` <- periodObject
      }
      if (!is.null(GamePlayAboutObject$`periodType`)) {
        self$`periodType` <- GamePlayAboutObject$`periodType`
      }
      if (!is.null(GamePlayAboutObject$`ordinalNum`)) {
        self$`ordinalNum` <- GamePlayAboutObject$`ordinalNum`
      }
      if (!is.null(GamePlayAboutObject$`periodTime`)) {
        self$`periodTime` <- GamePlayAboutObject$`periodTime`
      }
      if (!is.null(GamePlayAboutObject$`periodTimeRemaining`)) {
        self$`periodTimeRemaining` <- GamePlayAboutObject$`periodTimeRemaining`
      }
      if (!is.null(GamePlayAboutObject$`dateTime`)) {
        self$`dateTime` <- GamePlayAboutObject$`dateTime`
      }
      if (!is.null(GamePlayAboutObject$`goals`)) {
        goalsObject <- GamePlayAboutGoals$new()
        goalsObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$goals, auto_unbox = TRUE))
        self$`goals` <- goalsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "eventIdx": %s,
           "eventId": %s,
           "period": %s,
           "periodType": %s,
           "ordinalNum": %s,
           "periodTime": %s,
           "periodTimeRemaining": %s,
           "dateTime": %s,
           "goals": %s
        }',
        self$`eventIdx`$toJSON(),
        self$`eventId`$toJSON(),
        self$`period`$toJSON(),
        self$`periodType`,
        self$`ordinalNum`,
        self$`periodTime`,
        self$`periodTimeRemaining`,
        self$`dateTime`,
        self$`goals`$toJSON()
      )
    },
    fromJSONString = function(GamePlayAboutJson) {
      GamePlayAboutObject <- jsonlite::fromJSON(GamePlayAboutJson)
      BigDecimalObject <- BigDecimal$new()
      self$`eventIdx` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$eventIdx, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`eventId` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$eventId, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`period` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$period, auto_unbox = TRUE))
      self$`periodType` <- GamePlayAboutObject$`periodType`
      self$`ordinalNum` <- GamePlayAboutObject$`ordinalNum`
      self$`periodTime` <- GamePlayAboutObject$`periodTime`
      self$`periodTimeRemaining` <- GamePlayAboutObject$`periodTimeRemaining`
      self$`dateTime` <- GamePlayAboutObject$`dateTime`
      GamePlayAboutGoalsObject <- GamePlayAboutGoals$new()
      self$`goals` <- GamePlayAboutGoalsObject$fromJSON(jsonlite::toJSON(GamePlayAboutObject$goals, auto_unbox = TRUE))
    }
  )
)
