# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameMediaAudio Class
#'
#' @field title 
#' @field items 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameMediaAudio <- R6::R6Class(
  'GameMediaAudio',
  public = list(
    title = NULL,
    items = NULL,
    initialize = function(title, items){
      if (!missing(title)) {
        stopifnot(is.character(title), length(title) == 1)
        self$title <- title
      }
      if (!missing(items)) {
        stopifnot(is.list(items), length(items) != 0)
        lapply(items, function(x) stopifnot(R6::is.R6(x)))
        self$items <- items
      }
    },
    toJSON = function() {
      GameMediaAudioObject <- list()
      if (!is.null(self$title)) {
        GameMediaAudioObject[['title']] <- self$title
      }
      if (!is.null(self$items)) {
        GameMediaAudioObject[['items']] <- lapply(self$items, function(x) x$toJSON())
      }

      GameMediaAudioObject
    },
    fromJSON = function(GameMediaAudioJson) {
      GameMediaAudioObject <- jsonlite::fromJSON(GameMediaAudioJson)
      if (!is.null(GameMediaAudioObject$title)) {
        self$title <- GameMediaAudioObject$title
      }
      if (!is.null(GameMediaAudioObject$items)) {
        self$items <- lapply(GameMediaAudioObject$items, function(x) {
          itemsObject <- GameMediaAudioItems$new()
          itemsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          itemsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": %s,
           "items": [%s]
        }',
        self$title,
        lapply(self$items, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GameMediaAudioJson) {
      GameMediaAudioObject <- jsonlite::fromJSON(GameMediaAudioJson)
      self$title <- GameMediaAudioObject$title
      self$items <- lapply(GameMediaAudioObject$items, function(x) GameMediaAudioItems$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
