# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameDecisionPlayer Class
#'
#' @field id 
#' @field fullName 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameDecisionPlayer <- R6::R6Class(
  'GameDecisionPlayer',
  public = list(
    id = NULL,
    fullName = NULL,
    link = NULL,
    initialize = function(id, fullName, link){
      if (!missing(id)) {
        stopifnot(is.numeric(id), length(id) == 1)
        stopifnot(R6::is.R6(id))
        self$id <- id
      }
      if (!missing(fullName)) {
        stopifnot(is.character(fullName), length(fullName) == 1)
        self$fullName <- fullName
      }
      if (!missing(link)) {
        stopifnot(is.character(link), length(link) == 1)
        self$link <- link
      }
    },
    toJSON = function() {
      GameDecisionPlayerObject <- list()
      if (!is.null(self$id)) {
        GameDecisionPlayerObject[['id']] <- self$id$toJSON()
      }
      if (!is.null(self$fullName)) {
        GameDecisionPlayerObject[['fullName']] <- self$fullName
      }
      if (!is.null(self$link)) {
        GameDecisionPlayerObject[['link']] <- self$link
      }

      GameDecisionPlayerObject
    },
    fromJSON = function(GameDecisionPlayerJson) {
      GameDecisionPlayerObject <- jsonlite::fromJSON(GameDecisionPlayerJson)
      if (!is.null(GameDecisionPlayerObject$id)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(GameDecisionPlayerObject$id, auto_unbox = TRUE))
        self$id <- idObject
      }
      if (!is.null(GameDecisionPlayerObject$fullName)) {
        self$fullName <- GameDecisionPlayerObject$fullName
      }
      if (!is.null(GameDecisionPlayerObject$link)) {
        self$link <- GameDecisionPlayerObject$link
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "fullName": %s,
           "link": %s
        }',
        self$id$toJSON(),
        self$fullName,
        self$link
      )
    },
    fromJSONString = function(GameDecisionPlayerJson) {
      GameDecisionPlayerObject <- jsonlite::fromJSON(GameDecisionPlayerJson)
      BigDecimalObject <- BigDecimal$new()
      self$id <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameDecisionPlayerObject$id, auto_unbox = TRUE))
      self$fullName <- GameDecisionPlayerObject$fullName
      self$link <- GameDecisionPlayerObject$link
    }
  )
)
