# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GameBoxscoreTeamOnIcePlus Class
#'
#' @field playerId 
#' @field shiftDuration 
#' @field stamina 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GameBoxscoreTeamOnIcePlus <- R6::R6Class(
  'GameBoxscoreTeamOnIcePlus',
  public = list(
    playerId = NULL,
    shiftDuration = NULL,
    stamina = NULL,
    initialize = function(playerId, shiftDuration, stamina){
      if (!missing(playerId)) {
        stopifnot(is.numeric(playerId), length(playerId) == 1)
        stopifnot(R6::is.R6(playerId))
        self$playerId <- playerId
      }
      if (!missing(shiftDuration)) {
        stopifnot(is.numeric(shiftDuration), length(shiftDuration) == 1)
        stopifnot(R6::is.R6(shiftDuration))
        self$shiftDuration <- shiftDuration
      }
      if (!missing(stamina)) {
        stopifnot(is.numeric(stamina), length(stamina) == 1)
        stopifnot(R6::is.R6(stamina))
        self$stamina <- stamina
      }
    },
    toJSON = function() {
      GameBoxscoreTeamOnIcePlusObject <- list()
      if (!is.null(self$playerId)) {
        GameBoxscoreTeamOnIcePlusObject[['playerId']] <- self$playerId$toJSON()
      }
      if (!is.null(self$shiftDuration)) {
        GameBoxscoreTeamOnIcePlusObject[['shiftDuration']] <- self$shiftDuration$toJSON()
      }
      if (!is.null(self$stamina)) {
        GameBoxscoreTeamOnIcePlusObject[['stamina']] <- self$stamina$toJSON()
      }

      GameBoxscoreTeamOnIcePlusObject
    },
    fromJSON = function(GameBoxscoreTeamOnIcePlusJson) {
      GameBoxscoreTeamOnIcePlusObject <- jsonlite::fromJSON(GameBoxscoreTeamOnIcePlusJson)
      if (!is.null(GameBoxscoreTeamOnIcePlusObject$playerId)) {
        playerIdObject <- BigDecimal$new()
        playerIdObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$playerId, auto_unbox = TRUE))
        self$playerId <- playerIdObject
      }
      if (!is.null(GameBoxscoreTeamOnIcePlusObject$shiftDuration)) {
        shiftDurationObject <- BigDecimal$new()
        shiftDurationObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$shiftDuration, auto_unbox = TRUE))
        self$shiftDuration <- shiftDurationObject
      }
      if (!is.null(GameBoxscoreTeamOnIcePlusObject$stamina)) {
        staminaObject <- BigDecimal$new()
        staminaObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$stamina, auto_unbox = TRUE))
        self$stamina <- staminaObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "playerId": %s,
           "shiftDuration": %s,
           "stamina": %s
        }',
        self$playerId$toJSON(),
        self$shiftDuration$toJSON(),
        self$stamina$toJSON()
      )
    },
    fromJSONString = function(GameBoxscoreTeamOnIcePlusJson) {
      GameBoxscoreTeamOnIcePlusObject <- jsonlite::fromJSON(GameBoxscoreTeamOnIcePlusJson)
      BigDecimalObject <- BigDecimal$new()
      self$playerId <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$playerId, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$shiftDuration <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$shiftDuration, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$stamina <- BigDecimalObject$fromJSON(jsonlite::toJSON(GameBoxscoreTeamOnIcePlusObject$stamina, auto_unbox = TRUE))
    }
  )
)
