# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' GamePlayAboutGoals Class
#'
#' @field away 
#' @field home 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GamePlayAboutGoals <- R6::R6Class(
  'GamePlayAboutGoals',
  public = list(
    `away` = NULL,
    `home` = NULL,
    initialize = function(`away`, `home`){
      if (!missing(`away`)) {
        stopifnot(is.numeric(`away`), length(`away`) == 1)
        stopifnot(R6::is.R6(`away`))
        self$`away` <- `away`
      }
      if (!missing(`home`)) {
        stopifnot(is.numeric(`home`), length(`home`) == 1)
        stopifnot(R6::is.R6(`home`))
        self$`home` <- `home`
      }
    },
    toJSON = function() {
      GamePlayAboutGoalsObject <- list()
      if (!is.null(self$`away`)) {
        GamePlayAboutGoalsObject[['away']] <- self$`away`$toJSON()
      }
      if (!is.null(self$`home`)) {
        GamePlayAboutGoalsObject[['home']] <- self$`home`$toJSON()
      }

      GamePlayAboutGoalsObject
    },
    fromJSON = function(GamePlayAboutGoalsJson) {
      GamePlayAboutGoalsObject <- jsonlite::fromJSON(GamePlayAboutGoalsJson)
      if (!is.null(GamePlayAboutGoalsObject$`away`)) {
        awayObject <- BigDecimal$new()
        awayObject$fromJSON(jsonlite::toJSON(GamePlayAboutGoalsObject$away, auto_unbox = TRUE))
        self$`away` <- awayObject
      }
      if (!is.null(GamePlayAboutGoalsObject$`home`)) {
        homeObject <- BigDecimal$new()
        homeObject$fromJSON(jsonlite::toJSON(GamePlayAboutGoalsObject$home, auto_unbox = TRUE))
        self$`home` <- homeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "away": %s,
           "home": %s
        }',
        self$`away`$toJSON(),
        self$`home`$toJSON()
      )
    },
    fromJSONString = function(GamePlayAboutGoalsJson) {
      GamePlayAboutGoalsObject <- jsonlite::fromJSON(GamePlayAboutGoalsJson)
      BigDecimalObject <- BigDecimal$new()
      self$`away` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GamePlayAboutGoalsObject$away, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`home` <- BigDecimalObject$fromJSON(jsonlite::toJSON(GamePlayAboutGoalsObject$home, auto_unbox = TRUE))
    }
  )
)
