# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PlayerStatsOpponentDivision Class
#'
#' @field id 
#' @field name 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerStatsOpponentDivision <- R6::R6Class(
  'PlayerStatsOpponentDivision',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `link` = NULL,
    initialize = function(`id`, `name`, `link`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
    },
    toJSON = function() {
      PlayerStatsOpponentDivisionObject <- list()
      if (!is.null(self$`id`)) {
        PlayerStatsOpponentDivisionObject[['id']] <- self$`id`$toJSON()
      }
      if (!is.null(self$`name`)) {
        PlayerStatsOpponentDivisionObject[['name']] <- self$`name`
      }
      if (!is.null(self$`link`)) {
        PlayerStatsOpponentDivisionObject[['link']] <- self$`link`
      }

      PlayerStatsOpponentDivisionObject
    },
    fromJSON = function(PlayerStatsOpponentDivisionJson) {
      PlayerStatsOpponentDivisionObject <- jsonlite::fromJSON(PlayerStatsOpponentDivisionJson)
      if (!is.null(PlayerStatsOpponentDivisionObject$`id`)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(PlayerStatsOpponentDivisionObject$id, auto_unbox = TRUE))
        self$`id` <- idObject
      }
      if (!is.null(PlayerStatsOpponentDivisionObject$`name`)) {
        self$`name` <- PlayerStatsOpponentDivisionObject$`name`
      }
      if (!is.null(PlayerStatsOpponentDivisionObject$`link`)) {
        self$`link` <- PlayerStatsOpponentDivisionObject$`link`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "link": %s
        }',
        self$`id`$toJSON(),
        self$`name`,
        self$`link`
      )
    },
    fromJSONString = function(PlayerStatsOpponentDivisionJson) {
      PlayerStatsOpponentDivisionObject <- jsonlite::fromJSON(PlayerStatsOpponentDivisionJson)
      BigDecimalObject <- BigDecimal$new()
      self$`id` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PlayerStatsOpponentDivisionObject$id, auto_unbox = TRUE))
      self$`name` <- PlayerStatsOpponentDivisionObject$`name`
      self$`link` <- PlayerStatsOpponentDivisionObject$`link`
    }
  )
)
