# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PlayerStatsType Class
#'
#' @field displayName 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerStatsType <- R6::R6Class(
  'PlayerStatsType',
  public = list(
    displayName = NULL,
    initialize = function(displayName){
      if (!missing(displayName)) {
        stopifnot(is.character(displayName), length(displayName) == 1)
        self$displayName <- displayName
      }
    },
    toJSON = function() {
      PlayerStatsTypeObject <- list()
      if (!is.null(self$displayName)) {
        PlayerStatsTypeObject[['displayName']] <- self$displayName
      }

      PlayerStatsTypeObject
    },
    fromJSON = function(PlayerStatsTypeJson) {
      PlayerStatsTypeObject <- jsonlite::fromJSON(PlayerStatsTypeJson)
      if (!is.null(PlayerStatsTypeObject$displayName)) {
        self$displayName <- PlayerStatsTypeObject$displayName
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "displayName": %s
        }',
        self$displayName
      )
    },
    fromJSONString = function(PlayerStatsTypeJson) {
      PlayerStatsTypeObject <- jsonlite::fromJSON(PlayerStatsTypeJson)
      self$displayName <- PlayerStatsTypeObject$displayName
    }
  )
)
