# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PlayerCurrentTeam Class
#'
#' @field id 
#' @field name 
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PlayerCurrentTeam <- R6::R6Class(
  'PlayerCurrentTeam',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `link` = NULL,
    initialize = function(`id`, `name`, `link`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
    },
    toJSON = function() {
      PlayerCurrentTeamObject <- list()
      if (!is.null(self$`id`)) {
        PlayerCurrentTeamObject[['id']] <- self$`id`$toJSON()
      }
      if (!is.null(self$`name`)) {
        PlayerCurrentTeamObject[['name']] <- self$`name`
      }
      if (!is.null(self$`link`)) {
        PlayerCurrentTeamObject[['link']] <- self$`link`
      }

      PlayerCurrentTeamObject
    },
    fromJSON = function(PlayerCurrentTeamJson) {
      PlayerCurrentTeamObject <- jsonlite::fromJSON(PlayerCurrentTeamJson)
      if (!is.null(PlayerCurrentTeamObject$`id`)) {
        idObject <- BigDecimal$new()
        idObject$fromJSON(jsonlite::toJSON(PlayerCurrentTeamObject$id, auto_unbox = TRUE))
        self$`id` <- idObject
      }
      if (!is.null(PlayerCurrentTeamObject$`name`)) {
        self$`name` <- PlayerCurrentTeamObject$`name`
      }
      if (!is.null(PlayerCurrentTeamObject$`link`)) {
        self$`link` <- PlayerCurrentTeamObject$`link`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "name": %s,
           "link": %s
        }',
        self$`id`$toJSON(),
        self$`name`,
        self$`link`
      )
    },
    fromJSONString = function(PlayerCurrentTeamJson) {
      PlayerCurrentTeamObject <- jsonlite::fromJSON(PlayerCurrentTeamJson)
      BigDecimalObject <- BigDecimal$new()
      self$`id` <- BigDecimalObject$fromJSON(jsonlite::toJSON(PlayerCurrentTeamObject$id, auto_unbox = TRUE))
      self$`name` <- PlayerCurrentTeamObject$`name`
      self$`link` <- PlayerCurrentTeamObject$`link`
    }
  )
)
