# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScheduleDay Class
#'
#' @field date 
#' @field totalItems 
#' @field totalEvents 
#' @field totalGames 
#' @field totalMatches 
#' @field games 
#' @field events 
#' @field matches 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScheduleDay <- R6::R6Class(
  'ScheduleDay',
  public = list(
    date = NULL,
    totalItems = NULL,
    totalEvents = NULL,
    totalGames = NULL,
    totalMatches = NULL,
    games = NULL,
    events = NULL,
    matches = NULL,
    initialize = function(date, totalItems, totalEvents, totalGames, totalMatches, games, events, matches){
      if (!missing(date)) {
        stopifnot(is.character(date), length(date) == 1)
        self$date <- date
      }
      if (!missing(totalItems)) {
        stopifnot(is.numeric(totalItems), length(totalItems) == 1)
        stopifnot(R6::is.R6(totalItems))
        self$totalItems <- totalItems
      }
      if (!missing(totalEvents)) {
        stopifnot(is.numeric(totalEvents), length(totalEvents) == 1)
        stopifnot(R6::is.R6(totalEvents))
        self$totalEvents <- totalEvents
      }
      if (!missing(totalGames)) {
        stopifnot(is.numeric(totalGames), length(totalGames) == 1)
        stopifnot(R6::is.R6(totalGames))
        self$totalGames <- totalGames
      }
      if (!missing(totalMatches)) {
        stopifnot(is.numeric(totalMatches), length(totalMatches) == 1)
        stopifnot(R6::is.R6(totalMatches))
        self$totalMatches <- totalMatches
      }
      if (!missing(games)) {
        stopifnot(is.list(games), length(games) != 0)
        lapply(games, function(x) stopifnot(R6::is.R6(x)))
        self$games <- games
      }
      if (!missing(events)) {
        stopifnot(is.list(events), length(events) != 0)
        lapply(events, function(x) stopifnot(R6::is.R6(x)))
        self$events <- events
      }
      if (!missing(matches)) {
        stopifnot(is.list(matches), length(matches) != 0)
        lapply(matches, function(x) stopifnot(R6::is.R6(x)))
        self$matches <- matches
      }
    },
    toJSON = function() {
      ScheduleDayObject <- list()
      if (!is.null(self$date)) {
        ScheduleDayObject[['date']] <- self$date
      }
      if (!is.null(self$totalItems)) {
        ScheduleDayObject[['totalItems']] <- self$totalItems$toJSON()
      }
      if (!is.null(self$totalEvents)) {
        ScheduleDayObject[['totalEvents']] <- self$totalEvents$toJSON()
      }
      if (!is.null(self$totalGames)) {
        ScheduleDayObject[['totalGames']] <- self$totalGames$toJSON()
      }
      if (!is.null(self$totalMatches)) {
        ScheduleDayObject[['totalMatches']] <- self$totalMatches$toJSON()
      }
      if (!is.null(self$games)) {
        ScheduleDayObject[['games']] <- lapply(self$games, function(x) x$toJSON())
      }
      if (!is.null(self$events)) {
        ScheduleDayObject[['events']] <- lapply(self$events, function(x) x$toJSON())
      }
      if (!is.null(self$matches)) {
        ScheduleDayObject[['matches']] <- lapply(self$matches, function(x) x$toJSON())
      }

      ScheduleDayObject
    },
    fromJSON = function(ScheduleDayJson) {
      ScheduleDayObject <- jsonlite::fromJSON(ScheduleDayJson)
      if (!is.null(ScheduleDayObject$date)) {
        self$date <- ScheduleDayObject$date
      }
      if (!is.null(ScheduleDayObject$totalItems)) {
        totalItemsObject <- BigDecimal$new()
        totalItemsObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalItems, auto_unbox = TRUE))
        self$totalItems <- totalItemsObject
      }
      if (!is.null(ScheduleDayObject$totalEvents)) {
        totalEventsObject <- BigDecimal$new()
        totalEventsObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalEvents, auto_unbox = TRUE))
        self$totalEvents <- totalEventsObject
      }
      if (!is.null(ScheduleDayObject$totalGames)) {
        totalGamesObject <- BigDecimal$new()
        totalGamesObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalGames, auto_unbox = TRUE))
        self$totalGames <- totalGamesObject
      }
      if (!is.null(ScheduleDayObject$totalMatches)) {
        totalMatchesObject <- BigDecimal$new()
        totalMatchesObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalMatches, auto_unbox = TRUE))
        self$totalMatches <- totalMatchesObject
      }
      if (!is.null(ScheduleDayObject$games)) {
        self$games <- lapply(ScheduleDayObject$games, function(x) {
          gamesObject <- ScheduleGame$new()
          gamesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          gamesObject
        })
      }
      if (!is.null(ScheduleDayObject$events)) {
        self$events <- lapply(ScheduleDayObject$events, function(x) {
          eventsObject <- TODO_OBJECT_MAPPING$new()
          eventsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          eventsObject
        })
      }
      if (!is.null(ScheduleDayObject$matches)) {
        self$matches <- lapply(ScheduleDayObject$matches, function(x) {
          matchesObject <- TODO_OBJECT_MAPPING$new()
          matchesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          matchesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "date": %s,
           "totalItems": %s,
           "totalEvents": %s,
           "totalGames": %s,
           "totalMatches": %s,
           "games": [%s],
           "events": [%s],
           "matches": [%s]
        }',
        self$date,
        self$totalItems$toJSON(),
        self$totalEvents$toJSON(),
        self$totalGames$toJSON(),
        self$totalMatches$toJSON(),
        lapply(self$games, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$events, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$matches, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ScheduleDayJson) {
      ScheduleDayObject <- jsonlite::fromJSON(ScheduleDayJson)
      self$date <- ScheduleDayObject$date
      BigDecimalObject <- BigDecimal$new()
      self$totalItems <- BigDecimalObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalItems, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$totalEvents <- BigDecimalObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalEvents, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$totalGames <- BigDecimalObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalGames, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$totalMatches <- BigDecimalObject$fromJSON(jsonlite::toJSON(ScheduleDayObject$totalMatches, auto_unbox = TRUE))
      self$games <- lapply(ScheduleDayObject$games, function(x) ScheduleGame$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$events <- lapply(ScheduleDayObject$events, function(x) TODO_OBJECT_MAPPING$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$matches <- lapply(ScheduleDayObject$matches, function(x) TODO_OBJECT_MAPPING$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
