# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScheduleGameContent Class
#'
#' @field link 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScheduleGameContent <- R6::R6Class(
  'ScheduleGameContent',
  public = list(
    `link` = NULL,
    initialize = function(`link`){
      if (!missing(`link`)) {
        stopifnot(is.character(`link`), length(`link`) == 1)
        self$`link` <- `link`
      }
    },
    toJSON = function() {
      ScheduleGameContentObject <- list()
      if (!is.null(self$`link`)) {
        ScheduleGameContentObject[['link']] <- self$`link`
      }

      ScheduleGameContentObject
    },
    fromJSON = function(ScheduleGameContentJson) {
      ScheduleGameContentObject <- jsonlite::fromJSON(ScheduleGameContentJson)
      if (!is.null(ScheduleGameContentObject$`link`)) {
        self$`link` <- ScheduleGameContentObject$`link`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "link": %s
        }',
        self$`link`
      )
    },
    fromJSONString = function(ScheduleGameContentJson) {
      ScheduleGameContentObject <- jsonlite::fromJSON(ScheduleGameContentJson)
      self$`link` <- ScheduleGameContentObject$`link`
    }
  )
)
