# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScheduleGameTeamsAway Class
#'
#' @field leagueRecord 
#' @field score 
#' @field team 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScheduleGameTeamsAway <- R6::R6Class(
  'ScheduleGameTeamsAway',
  public = list(
    leagueRecord = NULL,
    score = NULL,
    team = NULL,
    initialize = function(leagueRecord, score, team){
      if (!missing(leagueRecord)) {
        stopifnot(R6::is.R6(leagueRecord))
        self$leagueRecord <- leagueRecord
      }
      if (!missing(score)) {
        stopifnot(is.numeric(score), length(score) == 1)
        stopifnot(R6::is.R6(score))
        self$score <- score
      }
      if (!missing(team)) {
        stopifnot(R6::is.R6(team))
        self$team <- team
      }
    },
    toJSON = function() {
      ScheduleGameTeamsAwayObject <- list()
      if (!is.null(self$leagueRecord)) {
        ScheduleGameTeamsAwayObject[['leagueRecord']] <- self$leagueRecord$toJSON()
      }
      if (!is.null(self$score)) {
        ScheduleGameTeamsAwayObject[['score']] <- self$score$toJSON()
      }
      if (!is.null(self$team)) {
        ScheduleGameTeamsAwayObject[['team']] <- self$team$toJSON()
      }

      ScheduleGameTeamsAwayObject
    },
    fromJSON = function(ScheduleGameTeamsAwayJson) {
      ScheduleGameTeamsAwayObject <- jsonlite::fromJSON(ScheduleGameTeamsAwayJson)
      if (!is.null(ScheduleGameTeamsAwayObject$leagueRecord)) {
        leagueRecordObject <- ScheduleGameTeamsAwayLeagueRecord$new()
        leagueRecordObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$leagueRecord, auto_unbox = TRUE))
        self$leagueRecord <- leagueRecordObject
      }
      if (!is.null(ScheduleGameTeamsAwayObject$score)) {
        scoreObject <- BigDecimal$new()
        scoreObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$score, auto_unbox = TRUE))
        self$score <- scoreObject
      }
      if (!is.null(ScheduleGameTeamsAwayObject$team)) {
        teamObject <- ScheduleGameTeamsAwayTeam$new()
        teamObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$team, auto_unbox = TRUE))
        self$team <- teamObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "leagueRecord": %s,
           "score": %s,
           "team": %s
        }',
        self$leagueRecord$toJSON(),
        self$score$toJSON(),
        self$team$toJSON()
      )
    },
    fromJSONString = function(ScheduleGameTeamsAwayJson) {
      ScheduleGameTeamsAwayObject <- jsonlite::fromJSON(ScheduleGameTeamsAwayJson)
      ScheduleGameTeamsAwayLeagueRecordObject <- ScheduleGameTeamsAwayLeagueRecord$new()
      self$leagueRecord <- ScheduleGameTeamsAwayLeagueRecordObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$leagueRecord, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$score <- BigDecimalObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$score, auto_unbox = TRUE))
      ScheduleGameTeamsAwayTeamObject <- ScheduleGameTeamsAwayTeam$new()
      self$team <- ScheduleGameTeamsAwayTeamObject$fromJSON(jsonlite::toJSON(ScheduleGameTeamsAwayObject$team, auto_unbox = TRUE))
    }
  )
)
