# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StatTypesInner Class
#'
#' @field displayName 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StatTypesInner <- R6::R6Class(
  'StatTypesInner',
  public = list(
    displayName = NULL,
    initialize = function(displayName){
      if (!missing(displayName)) {
        stopifnot(is.character(displayName), length(displayName) == 1)
        self$displayName <- displayName
      }
    },
    toJSON = function() {
      StatTypesInnerObject <- list()
      if (!is.null(self$displayName)) {
        StatTypesInnerObject[['displayName']] <- self$displayName
      }

      StatTypesInnerObject
    },
    fromJSON = function(StatTypesInnerJson) {
      StatTypesInnerObject <- jsonlite::fromJSON(StatTypesInnerJson)
      if (!is.null(StatTypesInnerObject$displayName)) {
        self$displayName <- StatTypesInnerObject$displayName
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "displayName": %s
        }',
        self$displayName
      )
    },
    fromJSONString = function(StatTypesInnerJson) {
      StatTypesInnerObject <- jsonlite::fromJSON(StatTypesInnerJson)
      self$displayName <- StatTypesInnerObject$displayName
    }
  )
)
