# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' TeamNextGameScheduleTeams Class
#'
#' @field away 
#' @field home 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamNextGameScheduleTeams <- R6::R6Class(
  'TeamNextGameScheduleTeams',
  public = list(
    away = NULL,
    home = NULL,
    initialize = function(away, home){
      if (!missing(away)) {
        stopifnot(R6::is.R6(away))
        self$away <- away
      }
      if (!missing(home)) {
        stopifnot(R6::is.R6(home))
        self$home <- home
      }
    },
    toJSON = function() {
      TeamNextGameScheduleTeamsObject <- list()
      if (!is.null(self$away)) {
        TeamNextGameScheduleTeamsObject[['away']] <- self$away$toJSON()
      }
      if (!is.null(self$home)) {
        TeamNextGameScheduleTeamsObject[['home']] <- self$home$toJSON()
      }

      TeamNextGameScheduleTeamsObject
    },
    fromJSON = function(TeamNextGameScheduleTeamsJson) {
      TeamNextGameScheduleTeamsObject <- jsonlite::fromJSON(TeamNextGameScheduleTeamsJson)
      if (!is.null(TeamNextGameScheduleTeamsObject$away)) {
        awayObject <- TeamNextGameScheduleTeamsAway$new()
        awayObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsObject$away, auto_unbox = TRUE))
        self$away <- awayObject
      }
      if (!is.null(TeamNextGameScheduleTeamsObject$home)) {
        homeObject <- TeamNextGameScheduleTeamsHome$new()
        homeObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsObject$home, auto_unbox = TRUE))
        self$home <- homeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "away": %s,
           "home": %s
        }',
        self$away$toJSON(),
        self$home$toJSON()
      )
    },
    fromJSONString = function(TeamNextGameScheduleTeamsJson) {
      TeamNextGameScheduleTeamsObject <- jsonlite::fromJSON(TeamNextGameScheduleTeamsJson)
      TeamNextGameScheduleTeamsAwayObject <- TeamNextGameScheduleTeamsAway$new()
      self$away <- TeamNextGameScheduleTeamsAwayObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsObject$away, auto_unbox = TRUE))
      TeamNextGameScheduleTeamsHomeObject <- TeamNextGameScheduleTeamsHome$new()
      self$home <- TeamNextGameScheduleTeamsHomeObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsObject$home, auto_unbox = TRUE))
    }
  )
)
