# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' TeamNextGameScheduleTeamsHomeLeagueRecord Class
#'
#' @field wins 
#' @field losses 
#' @field ot 
#' @field type 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TeamNextGameScheduleTeamsHomeLeagueRecord <- R6::R6Class(
  'TeamNextGameScheduleTeamsHomeLeagueRecord',
  public = list(
    wins = NULL,
    losses = NULL,
    ot = NULL,
    type = NULL,
    initialize = function(wins, losses, ot, type){
      if (!missing(wins)) {
        stopifnot(is.numeric(wins), length(wins) == 1)
        stopifnot(R6::is.R6(wins))
        self$wins <- wins
      }
      if (!missing(losses)) {
        stopifnot(is.numeric(losses), length(losses) == 1)
        stopifnot(R6::is.R6(losses))
        self$losses <- losses
      }
      if (!missing(ot)) {
        stopifnot(is.numeric(ot), length(ot) == 1)
        stopifnot(R6::is.R6(ot))
        self$ot <- ot
      }
      if (!missing(type)) {
        stopifnot(is.character(type), length(type) == 1)
        self$type <- type
      }
    },
    toJSON = function() {
      TeamNextGameScheduleTeamsHomeLeagueRecordObject <- list()
      if (!is.null(self$wins)) {
        TeamNextGameScheduleTeamsHomeLeagueRecordObject[['wins']] <- self$wins$toJSON()
      }
      if (!is.null(self$losses)) {
        TeamNextGameScheduleTeamsHomeLeagueRecordObject[['losses']] <- self$losses$toJSON()
      }
      if (!is.null(self$ot)) {
        TeamNextGameScheduleTeamsHomeLeagueRecordObject[['ot']] <- self$ot$toJSON()
      }
      if (!is.null(self$type)) {
        TeamNextGameScheduleTeamsHomeLeagueRecordObject[['type']] <- self$type
      }

      TeamNextGameScheduleTeamsHomeLeagueRecordObject
    },
    fromJSON = function(TeamNextGameScheduleTeamsHomeLeagueRecordJson) {
      TeamNextGameScheduleTeamsHomeLeagueRecordObject <- jsonlite::fromJSON(TeamNextGameScheduleTeamsHomeLeagueRecordJson)
      if (!is.null(TeamNextGameScheduleTeamsHomeLeagueRecordObject$wins)) {
        winsObject <- BigDecimal$new()
        winsObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$wins, auto_unbox = TRUE))
        self$wins <- winsObject
      }
      if (!is.null(TeamNextGameScheduleTeamsHomeLeagueRecordObject$losses)) {
        lossesObject <- BigDecimal$new()
        lossesObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$losses, auto_unbox = TRUE))
        self$losses <- lossesObject
      }
      if (!is.null(TeamNextGameScheduleTeamsHomeLeagueRecordObject$ot)) {
        otObject <- BigDecimal$new()
        otObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$ot, auto_unbox = TRUE))
        self$ot <- otObject
      }
      if (!is.null(TeamNextGameScheduleTeamsHomeLeagueRecordObject$type)) {
        self$type <- TeamNextGameScheduleTeamsHomeLeagueRecordObject$type
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "wins": %s,
           "losses": %s,
           "ot": %s,
           "type": %s
        }',
        self$wins$toJSON(),
        self$losses$toJSON(),
        self$ot$toJSON(),
        self$type
      )
    },
    fromJSONString = function(TeamNextGameScheduleTeamsHomeLeagueRecordJson) {
      TeamNextGameScheduleTeamsHomeLeagueRecordObject <- jsonlite::fromJSON(TeamNextGameScheduleTeamsHomeLeagueRecordJson)
      BigDecimalObject <- BigDecimal$new()
      self$wins <- BigDecimalObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$wins, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$losses <- BigDecimalObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$losses, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$ot <- BigDecimalObject$fromJSON(jsonlite::toJSON(TeamNextGameScheduleTeamsHomeLeagueRecordObject$ot, auto_unbox = TRUE))
      self$type <- TeamNextGameScheduleTeamsHomeLeagueRecordObject$type
    }
  )
)
