# NHL API
#
# Documenting the publicly accessible portions of the NHL API.
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Venue Class
#'
#' @field name 
#' @field link 
#' @field city 
#' @field timeZone 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Venue <- R6::R6Class(
  'Venue',
  public = list(
    name = NULL,
    link = NULL,
    city = NULL,
    timeZone = NULL,
    initialize = function(name, link, city, timeZone){
      if (!missing(name)) {
        stopifnot(is.character(name), length(name) == 1)
        self$name <- name
      }
      if (!missing(link)) {
        stopifnot(is.character(link), length(link) == 1)
        self$link <- link
      }
      if (!missing(city)) {
        stopifnot(is.character(city), length(city) == 1)
        self$city <- city
      }
      if (!missing(timeZone)) {
        stopifnot(R6::is.R6(timeZone))
        self$timeZone <- timeZone
      }
    },
    toJSON = function() {
      VenueObject <- list()
      if (!is.null(self$name)) {
        VenueObject[['name']] <- self$name
      }
      if (!is.null(self$link)) {
        VenueObject[['link']] <- self$link
      }
      if (!is.null(self$city)) {
        VenueObject[['city']] <- self$city
      }
      if (!is.null(self$timeZone)) {
        VenueObject[['timeZone']] <- self$timeZone$toJSON()
      }

      VenueObject
    },
    fromJSON = function(VenueJson) {
      VenueObject <- jsonlite::fromJSON(VenueJson)
      if (!is.null(VenueObject$name)) {
        self$name <- VenueObject$name
      }
      if (!is.null(VenueObject$link)) {
        self$link <- VenueObject$link
      }
      if (!is.null(VenueObject$city)) {
        self$city <- VenueObject$city
      }
      if (!is.null(VenueObject$timeZone)) {
        timeZoneObject <- VenueTimeZone$new()
        timeZoneObject$fromJSON(jsonlite::toJSON(VenueObject$timeZone, auto_unbox = TRUE))
        self$timeZone <- timeZoneObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "link": %s,
           "city": %s,
           "timeZone": %s
        }',
        self$name,
        self$link,
        self$city,
        self$timeZone$toJSON()
      )
    },
    fromJSONString = function(VenueJson) {
      VenueObject <- jsonlite::fromJSON(VenueJson)
      self$name <- VenueObject$name
      self$link <- VenueObject$link
      self$city <- VenueObject$city
      VenueTimeZoneObject <- VenueTimeZone$new()
      self$timeZone <- VenueTimeZoneObject$fromJSON(jsonlite::toJSON(VenueObject$timeZone, auto_unbox = TRUE))
    }
  )
)
